### ISSUE TITLE
role import

### ISSUE THREAD

**Issue by christophdb** [datamate-rethink-it/seafile-release#47]
wenn "False", dann geht es nicht. Wenn False in json, dann folgende Fehlermeldung...

Loading user role definitions from seafile_roles.json into seahub_settings.py...
Traceback (most recent call last):
  File "/scripts/generate-config-files.py", line 671, in <module>
    generate_seahub_settings_file(path=SEAHUB_SETTINGS_PATH)
  File "/scripts/generate-config-files.py", line 401, in generate_seahub_settings_file
    f'ENABLED_ROLE_PERMISSIONS = {repr(json.load(roles_file))}\n',
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 21 (char 37)

**Comment by christophdb** [comment]
wenn die Datei seafile_roles.json einmal gemountet wurde, dann ist sie drin. Wenn ich sie dann entferne, wird sie trotzdem verwendet... Problem?

**Comment by christophdb** [comment]
vielleicht lassen wir die seafile_roles.json einfach ganz weg. die overrides funktioniert wunderbar. Aber auch hier das problem: einmal gemountet, ist sie im conf verzeichnis drin... Problem?
